[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dao = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/skycoder/.config/solana/devnet.json "

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
